### ISSUE TITLE
Bug: v-if conditional questions do not work

### ISSUE THREAD

**Issue by andreasotto** [ditdot-dev/vue-flow-form#278] opened 2023-02-19 12:04 UTC
**Describe the bug**
Conditional questions do not work (causing javascript compile error in `false`-situation.

TypeError: Cannot read properties of undefined (reading 'indexOf')
in the computed questionModels getter method in this part of the code:

```
if (children) {
              children
                .filter(function (q) { return q.type && q.type.name.indexOf('Question') !== -1; })
                .forEach(function (q) {
````
The `filter` statement is the problem in a `v-if="false"`-condition.

**To Reproduce**

```
<template>
  <flow-form>
    <question id="one" type="number" title="Enter a number" v-model="form.number"></question>
    <question id="two" v-if="form.number !== 1" type="sectionbreak" title="Wrong number"></question>
  </flow-form>
</template>
```

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/2129515/219946147-9aeeb085-ccf9-4ed7-b3a8-35e9ee3dd57a.png)

![image](https://user-images.githubusercontent.com/2129515/219946165-09817ca1-b849-4b0e-a627-0e907c8a7536.png)

**Desktop (please complete the following information):**
 - vue 3.2.47
 - vite 3

**Additional context**
The questions with `v-if` conditions work fine as long as the condition is `true`. 
As soon as the condition is `false` the error occurs.
This means that the function cannot be used at all at the moment.

*If a small bounty is of interest, I'm happy to oblige.* 

**Any help would be greatly appreciated.**

**Comment by trevour66** [comment] 2023-06-12 07:02
I got to play around with this for quite some time and the issue comes from how question slots are processed.

_vue-flow-form/components/FlowForm.vue_
![image](https://github.com/ditdot-dev/vue-flow-form/assets/33531464/cecee659-9921-451e-8bf0-a51338b64312)

This is precisely where the problem the coming from. 

Logging _q_ shows this:
![image](https://github.com/ditdot-dev/vue-flow-form/assets/33531464/265d81cf-fd5c-453f-8c8b-b4e18bcf52fc)

One could see that _q_ has a property _children_, an array whose element(s) satisfies the requirement for the _filter_ operation to run successfully.

Let's implement this: 
![image](https://github.com/ditdot-dev/vue-flow-form/assets/33531464/a52f7e8f-d5eb-4cee-b408-3bb8b3e025ce)

The above edit appears to fix the problem. I acknowledge that it is not the best solution, however, it points out where the problem is coming from and a walkaround.

**Comment by andreasotto** [comment] 2023-06-12 07:09
Unfortunately, it looks like the project is no longer alive...?

**Comment by andreasotto** [comment] 2023-06-12 07:14
Yes, it is by far the best Vue forms library I have found after extensive research and several tests.

**Comment by spinn** [comment] 2023-06-13 16:38
This should now be fixed with the following commit:

https://github.com/ditdot-dev/vue-flow-form/commit/f2f20f63ee43309ea100d6ca342de4850b9c820a

We'll also be publishing the new version to npm soon.

**Closed** 2023-06-16 15:49 UTC
