### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by 6540140** [ditdot-dev/vue-flow-form#182] opened 2021-03-22 05:43 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
when make survey page, 
A page which contains two or more dropdown element is needed.
when I want to survey of elementary student, i should have to ask 'school name' + 'grade' + 'class' + 'number'..
when i use vue-flow-form..i should have to use 4 dropdown page..
if these things is in 1 page.. surveyer will happy.....

**Describe alternatives you've considered**

**Additional context**

**Comment by phre1** [comment] 2021-03-23 10:51
Thank you for your for the suggestion @6540140 . This is a duplicate of #131

**Closed by phre1** 2021-03-23 10:51 UTC
Labels: duplicate
